# Generated by Django 6.0.4 on 2026-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('injury_type', models.CharField(max_length=100)),
                ('fitness_level', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('body_part', models.CharField(max_length=100)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
